POST http://localhost:3000/signup
Content-Type: application/json

{
    "username":"test1",
    "password":"password1"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"test1",
    "password":"password1"
}

###

GET http://localhost:3000/test
Content-Type: application/json
Authorization: Bearer .eyJ1c2VybmFtZSI6InRlc3QxIiwicGFzc3dvcmQiOiJwYXNzd29yZDEiLCJpYXQiOjE3MjExNDM2MDYsImV4cCI6MTcyMTE0NzIwNn0.3Cx8hLe8DUP2uAGHsR1tAMle01Wv8TV0JR4IDMjz8Q0